### ISSUE TITLE
Not forcing emacs bindings if vi has been set

### ISSUE THREAD

**Issue by codeinabox** [tmux-plugins/tmux-sensible#19]
Can we change it so it doesn't force emacs bindings if vi has been set in the .vimrc? Assuming it's just a case of wrapping it in `option_value_not_changed` I'm happy to submit a PR.

**Comment by bruno-** [comment]
Hey, are you talking about `C-p` and `C-n` key bindings? We already have "guards" for these - [link to code](https://github.com/tmux-plugins/tmux-sensible/blob/master/sensible.tmux#L150-L156).

**Comment by codeinabox** [comment]
I was referring to the [setting for `status-keys`](https://github.com/tmux-plugins/tmux-sensible/blob/master/sensible.tmux#L108)

**Comment by bruno-** [comment]
Ah - that option. Are you really using `vi` mode for that? I'm all about vim, but tmux command line vi mode is \*horrible*.
And look, even [tpope has it explicitly set to emacs](https://github.com/tpope/tpope/blob/master/.tmux.conf#L2).

**Comment by codeinabox** [comment]
Fair play though is it tricky to wrap it in a `option_value_not_changed`? Otherwise happy for this issue to be closed

**Comment by bruno-** [comment]
Just revisiting this again.. I think it would be tricky to detect if a user explicitly set this option in his `tmux.conf`.

Here's from `$ man tmux`, `status-keys` option:

    The default is emacs, unless the VISUAL or EDITOR
    environment variables are set and contain the string `vi'.

So if a user has `EDITOR` set to `vi` or `vim`, this option will automatically be set to `vi` (which is not the default, but the user also didn't set it explicitly).

I don't see an (easy) way to check this so I'm closing the issue.
Feel free to reopen if you have some ideas.

**Comment by dragonxlwang** [comment]
sorry to bring this old thread again. I am new to the status-keys settings until across this plugin. Could you please tell me what's the difference in vi/emacs option in status-keys (not in copy mode)?  I tried to find related info and tried by myself but I don't see any notable differences.
