### ISSUE TITLE
OS X 10.10.4 breaks tmux-sensible

### ISSUE THREAD

**Issue by jcurtis** [tmux-plugins/tmux-sensible#25]
I just upgrade OS X to the latest 10.10.4 today and it disabled a few key features of tmux-sensible. Most notably the prefix has reverted to ctrl + b instead of ctrl + a. I can't seem to set it manually in the tmux.conf either. Any ideas here?

**Comment by bruno-** [comment]
Hey, that's unusual.
`tmux-sensible` does not set prefix though, you have to explicitly set it in `tmux.conf`. First release of this plugin favored `ctrl-a` for prefix but people didn't agree with this.

Other than prefix, what else is off?

**Comment by m1foley** [comment]
FWIW I just upgraded to 10.10.4 and don't notice a difference. I manually set the prefix to be C-Space in [my .tmux.conf](https://github.com/m1foley/dotfiles/blob/master/_tmux.conf#L33-L35).

**Comment by jcurtis** [comment]
@bruno- That must have been it. I had an old version of tmux-sensible. Sorry for the confusion.
