### ISSUE TITLE
Tmux attaching to already attached sessions on close.

### ISSUE THREAD

**Issue by edvinasme** [tmux-plugins/tmux-sensible#26]
Am I missing something regarding this option as it's quite annoying when using multiple tmux sessions in separate terminals. Every time I want to close tmux session, it attaches to some of the existing and already attaced-to tmux sessions. Is it possible to limit this to attach only to detached sessions?

I believe it is this setting that is causing this:

    # don't detach tmux when killing a session
    set -g detach-on-destroy off

**Comment by edvinasme** [comment]
As this seems to be ignored I am not using `tmux-sensible` anymore and using my own configuration plugin instead which has this and some other features that I find annoying not included.

If someone is interessted you can check https://github.com/edvinasme/tmux-config

Closing.

**Comment by bruno-** [comment]
Hey,
sorry for the late response. I wasn't ignoring this issue it just got lost in the sea of email..

You are right about `set -g detach-on-destroy off` - that's the one causing the behavior.
Per "plugins' policy" I've remove this option.

I'm glad people are creating their own tmux plugins!
