### ISSUE TITLE
What do you think about rebinding Ctrl-o?

### ISSUE THREAD

**Issue by oconnor663** [tmux-plugins/tmux-sensible#28]
I rebind `<prefix>ctrl-o` to be the same as `<prefix>o` in my config. For me it's in the same vein as the ctrl-n and ctrl-p bindings: easier to type, and I no longer accidentally swap my panes constantly all the time :) But because it's stomping on an existing biding, maybe it's not appropriate for the universal config. What do you think?

**Comment by bruno-** [comment]
Hey,
I'm not sure, I personally never got to using `prefix + o` or `prefix + ctrl-o`.

Can you get some people to upvote this idea so we can see how useful others find it?

**Comment by jonlorusso** [comment]
@oconnor663 So you use this instead of ctrl-p, ctrl-n (and presumably instead pane navigation jkl; as well)?

**Comment by oconnor663** [comment]
I use it instead of hjkl most of the time, because I rarely have more than two panes visible. Anyway, it seems like this is a pretty niche setting. Closing.
