### ISSUE TITLE
"Adaptable" key bindings not working for C-space prefix

### ISSUE THREAD

**Issue by aleprovencio** [tmux-plugins/tmux-sensible#31]
Hello @bruno- !

When I had `C-a` as my prefix tmux-sensible took care of binding `a` as the `last-window` shortcut. Now that I've set my prefix to `C-space`, I have to explicitly put a `bind Space last-window` on tmux.conf, so why tmux-sensible is not doing that by default?

**Comment by bruno-** [comment]
Good question.
This plugin being sensible and all won't override any existing bindings. Unfortunately the `Space` binding exists by default and is set to the `next-layout` command.
That's why a user has to manually override this binding.

**Comment by aleprovencio** [comment]
Got it :+1:
