### ISSUE TITLE
status-keys option is overridden by this plugin

### ISSUE THREAD

**Issue by dylan-chong** [tmux-plugins/tmux-sensible#43]
In the readme it says:

```
no overriding of user defined settings.
Your existing .tmux.conf settings are respected and they won't be changed.
```

However in my tmux.conf file, i have:

```
# ..
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g status-keys vi
run '~/.tmux/plugins/tpm/tpm'
```

My custom setting for status-keys are overridden, contradicting the readme

```
> tmux show -g status-keys
status-keys emacs
```

**Comment by bruno-** [comment]
I acknowledge this issue.

Please try putting `set -g status-keys vi` after `run '~/.tmux/plugins/tpm/tpm'` and things should work. (And yes `run '~/.tmux/plugins/tpm/tpm'` should be the last line in your `.tmux.conf`, but this will solve your problem)

Another suggestion is to give `emacs` mode a try. I'm all about `vim` but `emacs` mode really is better for single line editing. Even [tpope thinks so](https://github.com/tpope/tpope/blob/master/.tmux.conf#L17)

**Comment by dylan-chong** [comment]
Ah vi mode doesn't even support `f` and `F`! Ok yeah i've switched back to emacs mode

**Comment by bruno-** [comment]
Great, I'm closing the issue then. If someone thinks this is a problem, please report again.

**Comment by d13g0** [comment]
Hey @bruno- thanks for the great work on this plugin. I think that emacs vs. vi mode is a matter of preference. My suggestion to you is not to set this but leave it to the user. Thanks.
