### ISSUE TITLE
invalid option: utf8

### ISSUE THREAD

**Issue by planet36** [tmux-plugins/tmux-sensible#58]
Using these options gives an error.
```
set -g utf8 on
set -g status-utf8 on
```

```
invalid option: utf8
invalid option: status-utf8
```

`tmux -V`
> tmux 3.1c

**Comment by bruno-** [comment]
These where the options for an old tmux version. They were set in a way so they don't error in newer versions.

I guess it's ok to remove now. Fixed via https://github.com/tmux-plugins/tmux-sensible/commit/0dd7aed9a076e8e89e6be3c1227bcc5f43a5a800

**Comment by planet36** [comment]
Thanks. 
I didn't use the plugin -- I just copied what was in the README.md into my tmux conf.
