### ISSUE TITLE
Update readme to show defaults that are being changed

### ISSUE THREAD

**Issue by jjant** [tmux-plugins/tmux-sensible#65]
Hi, thank you for your work in this project.

In evaluating if I want to use this plugin, it'd be nice to have the default values for the options that are being modified in this snippet in the readme: https://github.com/tmux-plugins/tmux-sensible#options.

For example:
```diff
- # increase scrollback buffer size
+ # increase scrollback buffer size (default: 2000 lines)
set -g history-limit 50000
```

**Comment by bruno-** [comment]
That makes sense. Feel free to open a PR for this.

**Comment by jjant** [comment]
Done in #66.
