### ISSUE TITLE
Prefix key `<C-a>` conflicts with vim number increment and decrement

### ISSUE THREAD

**Issue by me-nkr** [tmux-plugins/tmux-sensible#67]
I think `<C-space>` could do a better job of not conflicting with vim.

**Comment by geoffreyvanwyk** [comment]
The default prefix is <kbd>Ctrl</kbd>+<kbd>B</kbd> according to the tmux wiki: https://github.com/tmux/tmux/wiki/Getting-Started#the-prefix-key

I cannot see where tmux-sensible changes it.

**Comment by me-nkr** [comment]
I think I mistook the following part in the readme

> "Adaptable" key bindings that build upon your `prefix` value:
> 
> ```tmux
> # If prefix is 'C-a'
> bind C-a send-prefix
> bind a last-window
> ```
> 
> If prefix is `C-b`, above keys will be `C-b` and `b`.<br/>
> If prefix is `C-z`, above keys will be `C-z` and `z`... you get the idea

sorry for the trouble.
