### ISSUE TITLE
Weird character string when tmux-sensible is enabled

### ISSUE THREAD

**Issue by cmonty14** [tmux-plugins/tmux-sensible#71]
Hi,
after enabling _tmux-sensible_ I get a weird character string in console when starting _tmux_; please check attached screenshot for details.

![image](https://github.com/tmux-plugins/tmux-sensible/assets/12523591/3f409932-b1e7-4f9b-8b42-2706e0a59b94)

Here's my _~/.config/tmux/tmux.conf:
```
# Upgrade $TERM
set -g default-terminal "screen-256color"
# Remap prefix from 'C-b' to 'C-s'
unbind C-b
set-option -g prefix C-d
bind-key C-d send-prefix
# Split panes using h and v
unbind '"'
unbind %
bind-key h split-window -h -c "#{pane_current_path}"
bind-key v split-window -v -c "#{pane_current_path}"
# Reload config file (change file location to your the tmux.conf you want to use)
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded."
# Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
# Shift-arrow to switch windows
bind -n C-Left previous-window
bind -n C-Right next-window
# Enable mouse control (clickable windows, panes, resizable panes)
#set -g mouse on
# Toggle mouse control
bind-key m set-option -g mouse \; display "Mouse: #{?mouse,On,Off}"
# Don't rename windows automatically
set-option -g allow-rename off
# Increase history
set-option -g history-limit 50000
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
# Automatic re-order windows
set -g renumber-windows on
# Reorder windows using Ctrl+Shift
bind-key C-Left swap-window -d -t -1
bind-key C-Right swap-window -d -t +1

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'
set -g @catppuccin_flavour 'mocha'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
```
Can you please advise how to fix this?

THX

**Comment by guru245** [comment]
I'm having the same issue and so I'm trying to find the cause. 

So far, this is what I've got:
tmux/focal-updates,focal-security,focal-updates,focal-security,now 3.0a-2ubuntu0.4 [Problem happens]
tmux/jammy-updates,jammy-security,now 3.2a-4ubuntu0.2 amd64  [No problem]

**Comment by cmonty14** [comment]
> I'm having the same issue and so I'm trying to find the cause.
> 
> So far, this is what I've got: tmux/focal-updates,focal-security,focal-updates,focal-security,now 3.0a-2ubuntu0.4 [Problem happens] tmux/jammy-updates,jammy-security,now 3.2a-4ubuntu0.2 amd64 [No problem]

Could you please share some additional information of your findings?
Are you saying that this problem depends on tmux version?

**Comment by guru245** [comment]
@cmonty14 Yes, exactly. When I use tmux 3.0, there is the problem. When I use tmux 3.2a, it's gone.

**Comment by cmonty14** [comment]
> @cmonty14 Yes, exactly. When I use tmux 3.0, there is the problem. When I use tmux 3.2a, it's gone.

OK.
I'm using tmux 3.1c, and the repos provide no newer version.

**Comment by guru245** [comment]
@cmonty14 I built it from the code. It was pretty easy.

**Comment by cmonty14** [comment]
Confirm that issue is not reproducible with tmux 3.3a
