### ISSUE TITLE
Tmux running in vscode terminal with `tmux-sensible` causes escape codes to appear

### ISSUE THREAD

**Issue by sinewalker** [tmux-plugins/tmux-sensible#73]
[VSCode's built-in terminal emulator](https://code.visualstudio.com/docs/terminal/basics) is based upon [xterm-js](https://github.com/xtermjs/xterm.js), which does not understand the ANSI terminal reset commands. When starting with `set-option -s escape-time 0`, then the following is inserted at the start of the session, and also whenever the terminal is resized:

```
^[]10;rgb:bebe/c6c6/d0d0^[\^[]11;rgb:0f0f/1212/1515^[\

~/l/t/p/tmux-sensible► ]10;rgb:bebe/c6c6/d0d0\]11;rgb:0f0f/1212/1515\  
```

[UPDATE/WORKAROUND](https://github.com/tmux-plugins/tmux-sensible/issues/73#issuecomment-2381392942):  Overriding [where it is set](https://github.com/tmux-plugins/tmux-sensible/blob/25cb91f42d020f675bb0a2ce3fbd3a5d96119efa/sensible.tmux#L82-L84) in `sensible.tmux` resolves this. You can do it from `tmux.conf` without altering the code in the plugin. Just set the option before loading `tmux-sensible`:

```config
set-option -s escape-time 10

# other settings...

run-shell ~/path/to/tpm/tpm

set-option -g @plugin 'tmux-plugins/tmux-sensible'
```

Similar to #24

**Comment by sinewalker** [comment]
I have tried this hack in `iterm_terminal` but it still gets called. I'm probably overlooking something simple:


```shell
iterm_terminal() {
	[[ "${TERM_PROGRAM}" =~ ^iTerm || "${LC_TERMINAL}" =~ ^iTerm || "${TERM_PROGRAM}" =~ ^vscode ]]
}
```

If I could work that out, then I'd make a PR.

**Comment by sinewalker** [comment]
> If I could work that out, then I'd make a PR.

To clarify, what I've tried so far (unsuccessfully) is

- Replace the last part of the condition with `true`
- Just replace that whole conditional line with `true`
- Replace the call to `iterm_terminal` on [line 123](https://github.com/tmux-plugins/tmux-sensible/blob/25cb91f42d020f675bb0a2ce3fbd3a5d96119efa/sensible.tmux#L123), with `true` (so `if ! true` which is false, no?) — I thought _that_ would at least stop it doing the `set-window-option` on line 124?!

**Comment by Honza-m** [comment]
I've run into the same problem, but I found that the setting that is causing the characters to appear is `escape-time`, as defined here on [line 82](https://github.com/tmux-plugins/tmux-sensible/blob/25cb91f42d020f675bb0a2ce3fbd3a5d96119efa/sensible.tmux#L82-L84). 

Putting this into my `tmux.conf` file fixes the issue for me, the characters no longer appear:
```
set-option -s escape-time 10
```

I don't know much about terminals so it's likely a combination of the two, but posting this here in case someone is looking for a quick solution to the problem.

**Comment by sinewalker** [comment]
> ```
> set-option -s escape-time 10
> ```
> 

This resolves for me, thank you @Honza-m !

To clarify for others: this setting can be placed before loading _tmux-sensible_ with TPM.

The option `escape-time` is described in the tmux manual:

> Set the time in milliseconds for which tmux waits after an escape is input to determine if it is part of a function or meta key sequences.  The default is 500 milliseconds.

So it makes sense for vim users to want to tune this down from 500ms, but _zero_ is too aggressive.
